# Generated by Django 3.0.6 on 2020-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restype', models.CharField(max_length=200)),
                ('spimgs', models.ImageField(upload_to='avatar/handleRquest/')),
                ('rescontent', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spname', models.CharField(max_length=255)),
                ('spimg', models.ImageField(upload_to='avatar/')),
                ('spcount', models.IntegerField()),
                ('spyujin', models.CharField(max_length=5)),
            ],
        ),
    ]
